In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
def number_normalization(source_num, source_min_num, source_max_num, target_min_num=0, target_max_num=1):
    dataset = np.array([source_min_num, source_num, source_max_num]).reshape(-1, 1)
    my_scaler = MinMaxScaler(feature_range=(target_min_num, target_max_num))  # 10分制
    new_dataset = my_scaler.fit_transform(dataset)
    target_num = new_dataset[1][0]
    return target_num

In [3]:
source_score = 17
source_min_score = -8
source_max_score = 42
target_min_score = 0
target_max_score = 1

In [4]:
target_score = number_normalization(source_score, source_min_score, source_max_score,
                                    target_min_score, target_max_score)
target_score

0.5

In [5]:
dataset = np.array([source_min_score, source_score, source_max_score]).reshape(-1, 1)

scaler = MinMaxScaler(feature_range=(target_min_score, target_max_score))  # 10分制

In [6]:
dataset

array([[-8],
       [17],
       [42]])

In [7]:
new_dataset = scaler.fit_transform(dataset)
new_dataset

array([[0. ],
       [0.5],
       [1. ]])

In [8]:
new_dataset[1]

array([0.5])

In [9]:
target_score = new_dataset[1][0]
target_score

0.5